// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/b10715018/ent-minimal-web-server/ent/runtime.go

const (
	Version = "v0.12.4-0.20230525114557-633d021f4860"           // Version of ent codegen.
	Sum     = "h1:UsjrAoHBDF7egT/R6wBcOW1X5GFfQfcsm3zqqd4SK9E=" // Sum of ent codegen.
)
